---
apiVersion: v1
kind: Namespace
metadata:
  name: onepassword

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: onepassword
  namespace: onepassword
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-connect-operator
  namespace: onepassword
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "1.10"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: onepassword
      interval: 12h
  values:
    connect:
      # NOTE: we're not supplying "credentials" key!
      # Instead a secret is expected to exist already with the contents of
      # "1password-credentials.json" as a base64 encoded value
      # See justfile for the command!
      credentialsName: onepassword-credential # name of secret
      credentialsKey: onepassword-credential # name of key in secret
    operator:
      # Also deploy the onepassword operator alongside the connect
      create: true
      token:
        # NOTE: we're not supplying the "value" key!
        # Instead, a secret is expected to exist already with Token
        # See justfile for the command!
        name: onepassword-token # name of secret
        key: token # name of key in secret