---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "20.8"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    logs:
      access:
        enable: true
        #filters:
          #statusCodes:
          #- "400-599" # Errors only.
    ingressRoute:
      dashboard:
        entryPoints: ["web", "websecure"]