---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "20.8"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    additionalArguments:
    # This is needed so that self-signed HTTPS from services
    # is ignored and passed through (Unifi-Controller)
    - "--serversTransport.insecureSkipVerify=true"
    ingressRoute:
      dashboard:
        entryPoints: ["web", "websecure"]
    # todo enable HTTPS redirect