apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        "Bergisch Gladbach": 1
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: onepassword
            name: onepassword-token
            key: token
