apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: onepassword
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect
      vaults:
        # "Bergisch Gladbach" vault # todo do IDs work here?
        saowjz663eddjhg4i3n5dy7l7m: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
