apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        "Bergisch Gladbach": 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
