---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "unifi-controller.web-interface" . }}-https-redirect
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: {{ include "unifi-controller.web-interface" . }}-transport
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
spec:
  # This is required because the container generates it's own HTTPS certificate
  # and the service only serves HTTPS traffic. Since the cert is self-generated,
  # it can't be verified reliably, so we just let it through.
  insecureSkipVerify: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "unifi-controller.web-interface" . }}
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
    - name: {{ include "unifi-controller.web-interface" . }}
      port: {{ .Values.webInterface.servicePort }}
      serversTransport: {{ include "unifi-controller.web-interface" . }}-transport
      scheme: https
    #middlewares:
    #- name: {{ include "unifi-controller.web-interface" . }}-https-redirect
