# Default values for pihole.

webInterface:
  servicePort: 80
  passwordSecretName:

ingress:
  host: pihole.local

pvc:
  storageClass: local-path

deployment:
  annotations: {}

external_dns: "8.8.8.8;8.8.4.4"

