# Default values for pihole.

webInterface:
  servicePort: 80

ingress:
  host: pihole.local

pvc:
  storageClass: local-path
  requestSize: 4Gi

deployment:
  annotations: {}

external_dns: "8.8.8.8;8.8.4.4"

backup:
  enabled: false
  secrets: []
  image: "ghcr.io/lukasknuth/backup-util:v3"
  schedule: "0 4 * * *"
  retryCount: 2
  # NOTE: Supply URL via Environment 'HEALTHCHECK_IO_URL'
  sendHealthcheckIo: false
  rotation:
    keepDaily: "3"
    keepWeekly: "2"
    keepMonthly: "6"
