apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
  - name: provisioners
  - name: configuration
  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/apps
  targetNamespace: apps
  interval: 60m0s # how often to detect drift and undo manual changes
  prune: true # remove any stale resources
  wait: true # wait for resources to become ready
  timeout: 5m # give up "wait" after x
  retryInterval: 1m # retry failures of apply/waiting
