apiVersion: v2
name: unifi-controller
description: Controller application for UniFi Access Points

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.2

# This is the docker image to be deployed with this application
appVersion: "7.3.76"
