# Default values for unifi-controller.

webInterface:
  servicePort: 443

pvc:
  storageClass: local-path
  requestSize: 20Gi

memory:
  limit: 1024
  startup: 1024

ingress:
  host: unifi-controller.local

backup:
  enabled: false
  secrets: []
  image: "ghcr.io/lukasknuth/backup-util:v3"
  schedule: "0 4 * * *"
  # NOTE: Supply URL via Environment 'HEALTHCHECK_IO_URL'
  sendHealthcheckIo: false
  rotation:
    keepDaily: "3"
    keepWeekly: "2"
    keepMonthly: "6"
