# Default values for unifi-controller.

webInterface:
  servicePort: 443

pvc:
  storageClass: local-path
  requestSize: 20Gi

memory:
  jre:
    startup: "default"
    limit: "default"
  k8s:
    request: "1024Mi"
    limit: null

ingress:
  host: unifi-controller.local

backup:
  enabled: false
  secrets: []
  image: "ghcr.io/lukasknuth/backup-util:v4"
  schedule: "0 4 * * *"
  retryCount: 2
  # NOTE: Supply URL via Environment 'HEALTHCHECK_IO_URL'
  sendHealthcheckIo: false
  rotation:
    keepDaily: "3"
    keepWeekly: "2"
    keepMonthly: "6"
