# Default values for unifi-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

webInterface:
  servicePort: 443

ingress:
  host: unifi-controller.local