apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.config-storage" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClass }}
  resources:
    requests:
      storage: 4Gi
