apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.config-storage" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi # Since "local-path" ignores this, what to chose?
