apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic-backup-secrets
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: &entry "restic_backup_config"
      property: access_key
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: *entry
      property: secret_access_key
  - secretKey: RESTIC_REPOSITORY
    remoteRef:
      key: *entry
      property: s3_url
  - secretKey: RESTIC_PASSWORD
    remoteRef:
      key: *entry
      property: password
