apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/pihole
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    external_dns: "5.1.66.255;185.150.99.255;2001:678:e68:f000::;2001:678:ed0:f000::"
    ingress:
      host: pihole.rpi
    deployment:
      annotations:
        operator.1password.io/item-name: &secret-name "pihole-webinterface-password"
        operator.1password.io/item-path: "vaults/saowjz663eddjhg4i3n5dy7l7m/items/djsngxz53vehpuqrmugeopz5my"
    webInterface:
      passwordSecretName: *secret-name
