#---
#apiVersion: external-secrets.io/v1beta1
#kind: ExternalSecret
#metadata:
  #name: pihole-secrets
#spec:
  #secretStoreRef:
    #kind: SecretStore
    #name: onepassword
    #namespace: onepassword
  #refreshInterval: 1h
  #target:
    #creationPolicy: Owner
  #data:
  #- secretKey: WEBPASSWORD
    #remoteRef:
      ## "PiHole" item # todo verify this supports IDs here
      #key: djsngxz53vehpuqrmugeopz5my
      ## the default password property of a 1Password entry
      #property: password

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/pihole
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    external_dns: "5.1.66.255;185.150.99.255;2001:678:e68:f000::;2001:678:ed0:f000::"
    ingress:
      host: pihole.rpi
    pvc:
      # todo cant auto do this. resolve manually to default
      requestSize: 2Gi
    webInterface:
      servicePort: 80
      #passwordSecretName: pihole-secrets
