---
apiVersion: v1
kind: Namespace
metadata:
  name: onepassword

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: onepassword
  namespace: onepassword
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: onepassword
spec:
  interval: 24h
  url: https://charts.external-secrets.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: onepassword
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.7"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: onepassword
      interval: 12h
  values: {}

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "1.10"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: onepassword
      interval: 12h
  values:
    connect:
      # NOTE: we're not supplying "credentials" key!
      # Instead a secret is expected to exist already with the contents of
      # "1password-credentials.json" as a base64 encoded value
      # See justfile for the command!
      credentialsName: onepassword-credentials # name of secret
      credentialsKey: onepassword-credentials # name of key in secret
    operator:
      # DON't deploy the onepassword operator, we use "external-secrets" instead
      create: false
