name: Build and Push `homeserver-replica-verify` Image

# This GitHub action builds a new image if any image-related files are updated
on:
  workflow_dispatch:
  push:
    paths:
    - 'maintenance/replica-verify/**'

permissions:
  # For uploading to Github Docker Registry
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: 'linux/amd64,linux/arm/v7,linux/arm64'
      REGISTRY: ghcr.io
      IMAGE_NAME: lukasknuth/homeserver-replica-verify
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Generate Container Metadata from git
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: push
        with:
          context: maintenance/replica-verify
          file: Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

